Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,11 +30,12 @@ jobs:
           action: build
         
       - name: run meson tests with sanitizers enabled (linux only)
+        id: meson-tests
         if: matrix.os == 'ubuntu-latest'
         run: |
           export ASAN_OPTIONS=abort_on_error=1:detect_leaks=0:log_path=asan
           export UBSAN_OPTIONS=print_stacktrace=1:halt_on_error=1
-          meson test -C build
+          meson test -C build || echo "status=failed" >> $GITHUB_OUTPUT
         continue-on-error: true
 
       - name: run meson tests with sanitizers disabled (windows only)
